package rolax.prueba.map;
// Generated Apr 28, 2016 11:06:22 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RespuestasCuestionarios generated by hbm2java
 */
public class RespuestasCuestionarios  implements java.io.Serializable {


     private String idCuestionario;
     private Usuario usuario;
     private String r1;
     private String r2;
     private String r3;
     private String r4;
     private String r5;
     private String r6;
     private String r7;
     private String r8;
     private String r9;
     private String r10;
     private String r11;
     private String r12;
     private String r13;
     private String r14;
     private String r15;
     private String r16;
     private String r17;
     private String r18;
     private String r19;
     private String r20;
     private String r21;
     private String r22;
     private String r23;
     private String r24;
     private String r25;
     private String r26;
     private String r27;
     private String r28;
     private String r29;
     private String r30;
     private String r31;
     private String r32;
     private String r33;
     private String r34;
     private String r35;
     private String r36;
     private String r37;
     private String r38;
     private String r39;
     private String r40;
     private String r41;
     private String r42;
     private String r43;
     private String r44;
     private String r45;
     private String r46;
     private String r47;
     private String r48;
     private String r49;
     private String r50;
     private String r51;
     private Date fechaRegistro;

    public RespuestasCuestionarios() {
    }

    public RespuestasCuestionarios(String idCuestionario, Usuario usuario, String r1, String r2, String r3, String r4, String r5, String r6, String r7, String r8, String r9, String r10, String r11, String r12, String r13, String r14, String r15, String r16, String r17, String r18, String r19, String r20, String r21, String r22, String r23, String r24, String r25, String r26, String r27, String r28, String r29, String r30, String r31, String r32, String r33, String r34, String r35, String r36, String r37, String r38, String r39, String r40, String r41, String r42, String r43, String r44, String r45, String r46, String r47, String r48, String r49, String r50, String r51, Date fechaRegistro) {
       this.idCuestionario = idCuestionario;
       this.usuario = usuario;
       this.r1 = r1;
       this.r2 = r2;
       this.r3 = r3;
       this.r4 = r4;
       this.r5 = r5;
       this.r6 = r6;
       this.r7 = r7;
       this.r8 = r8;
       this.r9 = r9;
       this.r10 = r10;
       this.r11 = r11;
       this.r12 = r12;
       this.r13 = r13;
       this.r14 = r14;
       this.r15 = r15;
       this.r16 = r16;
       this.r17 = r17;
       this.r18 = r18;
       this.r19 = r19;
       this.r20 = r20;
       this.r21 = r21;
       this.r22 = r22;
       this.r23 = r23;
       this.r24 = r24;
       this.r25 = r25;
       this.r26 = r26;
       this.r27 = r27;
       this.r28 = r28;
       this.r29 = r29;
       this.r30 = r30;
       this.r31 = r31;
       this.r32 = r32;
       this.r33 = r33;
       this.r34 = r34;
       this.r35 = r35;
       this.r36 = r36;
       this.r37 = r37;
       this.r38 = r38;
       this.r39 = r39;
       this.r40 = r40;
       this.r41 = r41;
       this.r42 = r42;
       this.r43 = r43;
       this.r44 = r44;
       this.r45 = r45;
       this.r46 = r46;
       this.r47 = r47;
       this.r48 = r48;
       this.r49 = r49;
       this.r50 = r50;
       this.r51 = r51;
       this.fechaRegistro = fechaRegistro;
    }
   
    public String getIdCuestionario() {
        return this.idCuestionario;
    }
    
    public void setIdCuestionario(String idCuestionario) {
        this.idCuestionario = idCuestionario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getR1() {
        return this.r1;
    }
    
    public void setR1(String r1) {
        this.r1 = r1;
    }
    public String getR2() {
        return this.r2;
    }
    
    public void setR2(String r2) {
        this.r2 = r2;
    }
    public String getR3() {
        return this.r3;
    }
    
    public void setR3(String r3) {
        this.r3 = r3;
    }
    public String getR4() {
        return this.r4;
    }
    
    public void setR4(String r4) {
        this.r4 = r4;
    }
    public String getR5() {
        return this.r5;
    }
    
    public void setR5(String r5) {
        this.r5 = r5;
    }
    public String getR6() {
        return this.r6;
    }
    
    public void setR6(String r6) {
        this.r6 = r6;
    }
    public String getR7() {
        return this.r7;
    }
    
    public void setR7(String r7) {
        this.r7 = r7;
    }
    public String getR8() {
        return this.r8;
    }
    
    public void setR8(String r8) {
        this.r8 = r8;
    }
    public String getR9() {
        return this.r9;
    }
    
    public void setR9(String r9) {
        this.r9 = r9;
    }
    public String getR10() {
        return this.r10;
    }
    
    public void setR10(String r10) {
        this.r10 = r10;
    }
    public String getR11() {
        return this.r11;
    }
    
    public void setR11(String r11) {
        this.r11 = r11;
    }
    public String getR12() {
        return this.r12;
    }
    
    public void setR12(String r12) {
        this.r12 = r12;
    }
    public String getR13() {
        return this.r13;
    }
    
    public void setR13(String r13) {
        this.r13 = r13;
    }
    public String getR14() {
        return this.r14;
    }
    
    public void setR14(String r14) {
        this.r14 = r14;
    }
    public String getR15() {
        return this.r15;
    }
    
    public void setR15(String r15) {
        this.r15 = r15;
    }
    public String getR16() {
        return this.r16;
    }
    
    public void setR16(String r16) {
        this.r16 = r16;
    }
    public String getR17() {
        return this.r17;
    }
    
    public void setR17(String r17) {
        this.r17 = r17;
    }
    public String getR18() {
        return this.r18;
    }
    
    public void setR18(String r18) {
        this.r18 = r18;
    }
    public String getR19() {
        return this.r19;
    }
    
    public void setR19(String r19) {
        this.r19 = r19;
    }
    public String getR20() {
        return this.r20;
    }
    
    public void setR20(String r20) {
        this.r20 = r20;
    }
    public String getR21() {
        return this.r21;
    }
    
    public void setR21(String r21) {
        this.r21 = r21;
    }
    public String getR22() {
        return this.r22;
    }
    
    public void setR22(String r22) {
        this.r22 = r22;
    }
    public String getR23() {
        return this.r23;
    }
    
    public void setR23(String r23) {
        this.r23 = r23;
    }
    public String getR24() {
        return this.r24;
    }
    
    public void setR24(String r24) {
        this.r24 = r24;
    }
    public String getR25() {
        return this.r25;
    }
    
    public void setR25(String r25) {
        this.r25 = r25;
    }
    public String getR26() {
        return this.r26;
    }
    
    public void setR26(String r26) {
        this.r26 = r26;
    }
    public String getR27() {
        return this.r27;
    }
    
    public void setR27(String r27) {
        this.r27 = r27;
    }
    public String getR28() {
        return this.r28;
    }
    
    public void setR28(String r28) {
        this.r28 = r28;
    }
    public String getR29() {
        return this.r29;
    }
    
    public void setR29(String r29) {
        this.r29 = r29;
    }
    public String getR30() {
        return this.r30;
    }
    
    public void setR30(String r30) {
        this.r30 = r30;
    }
    public String getR31() {
        return this.r31;
    }
    
    public void setR31(String r31) {
        this.r31 = r31;
    }
    public String getR32() {
        return this.r32;
    }
    
    public void setR32(String r32) {
        this.r32 = r32;
    }
    public String getR33() {
        return this.r33;
    }
    
    public void setR33(String r33) {
        this.r33 = r33;
    }
    public String getR34() {
        return this.r34;
    }
    
    public void setR34(String r34) {
        this.r34 = r34;
    }
    public String getR35() {
        return this.r35;
    }
    
    public void setR35(String r35) {
        this.r35 = r35;
    }
    public String getR36() {
        return this.r36;
    }
    
    public void setR36(String r36) {
        this.r36 = r36;
    }
    public String getR37() {
        return this.r37;
    }
    
    public void setR37(String r37) {
        this.r37 = r37;
    }
    public String getR38() {
        return this.r38;
    }
    
    public void setR38(String r38) {
        this.r38 = r38;
    }
    public String getR39() {
        return this.r39;
    }
    
    public void setR39(String r39) {
        this.r39 = r39;
    }
    public String getR40() {
        return this.r40;
    }
    
    public void setR40(String r40) {
        this.r40 = r40;
    }
    public String getR41() {
        return this.r41;
    }
    
    public void setR41(String r41) {
        this.r41 = r41;
    }
    public String getR42() {
        return this.r42;
    }
    
    public void setR42(String r42) {
        this.r42 = r42;
    }
    public String getR43() {
        return this.r43;
    }
    
    public void setR43(String r43) {
        this.r43 = r43;
    }
    public String getR44() {
        return this.r44;
    }
    
    public void setR44(String r44) {
        this.r44 = r44;
    }
    public String getR45() {
        return this.r45;
    }
    
    public void setR45(String r45) {
        this.r45 = r45;
    }
    public String getR46() {
        return this.r46;
    }
    
    public void setR46(String r46) {
        this.r46 = r46;
    }
    public String getR47() {
        return this.r47;
    }
    
    public void setR47(String r47) {
        this.r47 = r47;
    }
    public String getR48() {
        return this.r48;
    }
    
    public void setR48(String r48) {
        this.r48 = r48;
    }
    public String getR49() {
        return this.r49;
    }
    
    public void setR49(String r49) {
        this.r49 = r49;
    }
    public String getR50() {
        return this.r50;
    }
    
    public void setR50(String r50) {
        this.r50 = r50;
    }
    public String getR51() {
        return this.r51;
    }
    
    public void setR51(String r51) {
        this.r51 = r51;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


