package rolax.prueba.map;
// Generated Apr 28, 2016 11:06:22 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String idUsuario;
     private String nombre;
     private String codigo;
     private int cantidadLlenado;
     private Date fechaLlenado1;
     private Date fechaRegistro;
     private Set respuestasCuestionarioses = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String idUsuario, String nombre, String codigo, int cantidadLlenado, Date fechaLlenado1, Date fechaRegistro) {
        this.idUsuario = idUsuario;
        this.nombre = nombre;
        this.codigo = codigo;
        this.cantidadLlenado = cantidadLlenado;
        this.fechaLlenado1 = fechaLlenado1;
        this.fechaRegistro = fechaRegistro;
    }
    public Usuario(String idUsuario, String nombre, String codigo, int cantidadLlenado, Date fechaLlenado1, Date fechaRegistro, Set respuestasCuestionarioses) {
       this.idUsuario = idUsuario;
       this.nombre = nombre;
       this.codigo = codigo;
       this.cantidadLlenado = cantidadLlenado;
       this.fechaLlenado1 = fechaLlenado1;
       this.fechaRegistro = fechaRegistro;
       this.respuestasCuestionarioses = respuestasCuestionarioses;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public int getCantidadLlenado() {
        return this.cantidadLlenado;
    }
    
    public void setCantidadLlenado(int cantidadLlenado) {
        this.cantidadLlenado = cantidadLlenado;
    }
    public Date getFechaLlenado1() {
        return this.fechaLlenado1;
    }
    
    public void setFechaLlenado1(Date fechaLlenado1) {
        this.fechaLlenado1 = fechaLlenado1;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set getRespuestasCuestionarioses() {
        return this.respuestasCuestionarioses;
    }
    
    public void setRespuestasCuestionarioses(Set respuestasCuestionarioses) {
        this.respuestasCuestionarioses = respuestasCuestionarioses;
    }




}


